# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConfuseDemo1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConfuseDemo1

  target 'ConfuseDemo1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConfuseDemo1UITests' do
    # Pods for testing
  end

end
